better documentation, print sql commands, verify database connection

diff --git a/docker-entry b/docker-entry
--- a/docker-entry
+++ b/docker-entry
@@ -1,12 +1,15 @@
 #!/bin/sh
 
-sleep 10
+if ! psql -c "SELECT version()"; then
+  echo "Failed to connect to database"
+  exit 1
+fi
 
 echo "Starting DB maintenance"
 
 for f in /var/opt/psql/scripts.d/*.sql; do
   echo "Running $f"
-  psql -f "$f"
+  psql -a -f "$f"
 done
 
 echo "DB maintenance complete"
